// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitea.risky.info/risky-info/gossiper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldData, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPassword, v))
}

// SMTPHost applies equality check predicate on the "smtp_host" field. It's identical to SMTPHostEQ.
func SMTPHost(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSMTPHost, v))
}

// SMTPPort applies equality check predicate on the "smtp_port" field. It's identical to SMTPPortEQ.
func SMTPPort(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSMTPPort, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldURL, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v Method) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v Method) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...Method) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...Method) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldMethod, vs...))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldData, v))
}

// DataContains applies the Contains predicate on the "data" field.
func DataContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldData, v))
}

// DataHasPrefix applies the HasPrefix predicate on the "data" field.
func DataHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldData, v))
}

// DataHasSuffix applies the HasSuffix predicate on the "data" field.
func DataHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldData, v))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldData))
}

// DataEqualFold applies the EqualFold predicate on the "data" field.
func DataEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldData, v))
}

// DataContainsFold applies the ContainsFold predicate on the "data" field.
func DataContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldData, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldPassword, v))
}

// SMTPHostEQ applies the EQ predicate on the "smtp_host" field.
func SMTPHostEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSMTPHost, v))
}

// SMTPHostNEQ applies the NEQ predicate on the "smtp_host" field.
func SMTPHostNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSMTPHost, v))
}

// SMTPHostIn applies the In predicate on the "smtp_host" field.
func SMTPHostIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSMTPHost, vs...))
}

// SMTPHostNotIn applies the NotIn predicate on the "smtp_host" field.
func SMTPHostNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSMTPHost, vs...))
}

// SMTPHostGT applies the GT predicate on the "smtp_host" field.
func SMTPHostGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSMTPHost, v))
}

// SMTPHostGTE applies the GTE predicate on the "smtp_host" field.
func SMTPHostGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSMTPHost, v))
}

// SMTPHostLT applies the LT predicate on the "smtp_host" field.
func SMTPHostLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSMTPHost, v))
}

// SMTPHostLTE applies the LTE predicate on the "smtp_host" field.
func SMTPHostLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSMTPHost, v))
}

// SMTPHostContains applies the Contains predicate on the "smtp_host" field.
func SMTPHostContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldSMTPHost, v))
}

// SMTPHostHasPrefix applies the HasPrefix predicate on the "smtp_host" field.
func SMTPHostHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldSMTPHost, v))
}

// SMTPHostHasSuffix applies the HasSuffix predicate on the "smtp_host" field.
func SMTPHostHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldSMTPHost, v))
}

// SMTPHostIsNil applies the IsNil predicate on the "smtp_host" field.
func SMTPHostIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldSMTPHost))
}

// SMTPHostNotNil applies the NotNil predicate on the "smtp_host" field.
func SMTPHostNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldSMTPHost))
}

// SMTPHostEqualFold applies the EqualFold predicate on the "smtp_host" field.
func SMTPHostEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldSMTPHost, v))
}

// SMTPHostContainsFold applies the ContainsFold predicate on the "smtp_host" field.
func SMTPHostContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldSMTPHost, v))
}

// SMTPPortEQ applies the EQ predicate on the "smtp_port" field.
func SMTPPortEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSMTPPort, v))
}

// SMTPPortNEQ applies the NEQ predicate on the "smtp_port" field.
func SMTPPortNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSMTPPort, v))
}

// SMTPPortIn applies the In predicate on the "smtp_port" field.
func SMTPPortIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSMTPPort, vs...))
}

// SMTPPortNotIn applies the NotIn predicate on the "smtp_port" field.
func SMTPPortNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSMTPPort, vs...))
}

// SMTPPortGT applies the GT predicate on the "smtp_port" field.
func SMTPPortGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSMTPPort, v))
}

// SMTPPortGTE applies the GTE predicate on the "smtp_port" field.
func SMTPPortGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSMTPPort, v))
}

// SMTPPortLT applies the LT predicate on the "smtp_port" field.
func SMTPPortLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSMTPPort, v))
}

// SMTPPortLTE applies the LTE predicate on the "smtp_port" field.
func SMTPPortLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSMTPPort, v))
}

// SMTPPortIsNil applies the IsNil predicate on the "smtp_port" field.
func SMTPPortIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldSMTPPort))
}

// SMTPPortNotNil applies the NotNil predicate on the "smtp_port" field.
func SMTPPortNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldSMTPPort))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
