// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"gitea.risky.info/risky-info/gossiper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmail, v))
}

// FromRegex applies equality check predicate on the "from_regex" field. It's identical to FromRegexEQ.
func FromRegex(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFromRegex, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// PayloadTemplate applies equality check predicate on the "payload_template" field. It's identical to PayloadTemplateEQ.
func PayloadTemplate(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPayloadTemplate, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldEmail, v))
}

// FromRegexEQ applies the EQ predicate on the "from_regex" field.
func FromRegexEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFromRegex, v))
}

// FromRegexNEQ applies the NEQ predicate on the "from_regex" field.
func FromRegexNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFromRegex, v))
}

// FromRegexIn applies the In predicate on the "from_regex" field.
func FromRegexIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFromRegex, vs...))
}

// FromRegexNotIn applies the NotIn predicate on the "from_regex" field.
func FromRegexNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFromRegex, vs...))
}

// FromRegexGT applies the GT predicate on the "from_regex" field.
func FromRegexGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFromRegex, v))
}

// FromRegexGTE applies the GTE predicate on the "from_regex" field.
func FromRegexGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFromRegex, v))
}

// FromRegexLT applies the LT predicate on the "from_regex" field.
func FromRegexLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFromRegex, v))
}

// FromRegexLTE applies the LTE predicate on the "from_regex" field.
func FromRegexLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFromRegex, v))
}

// FromRegexContains applies the Contains predicate on the "from_regex" field.
func FromRegexContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldFromRegex, v))
}

// FromRegexHasPrefix applies the HasPrefix predicate on the "from_regex" field.
func FromRegexHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldFromRegex, v))
}

// FromRegexHasSuffix applies the HasSuffix predicate on the "from_regex" field.
func FromRegexHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldFromRegex, v))
}

// FromRegexEqualFold applies the EqualFold predicate on the "from_regex" field.
func FromRegexEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldFromRegex, v))
}

// FromRegexContainsFold applies the ContainsFold predicate on the "from_regex" field.
func FromRegexContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldFromRegex, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldURL, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v Method) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v Method) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...Method) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...Method) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldMethod, vs...))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldHeaders))
}

// PayloadTemplateEQ applies the EQ predicate on the "payload_template" field.
func PayloadTemplateEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPayloadTemplate, v))
}

// PayloadTemplateNEQ applies the NEQ predicate on the "payload_template" field.
func PayloadTemplateNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldPayloadTemplate, v))
}

// PayloadTemplateIn applies the In predicate on the "payload_template" field.
func PayloadTemplateIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldPayloadTemplate, vs...))
}

// PayloadTemplateNotIn applies the NotIn predicate on the "payload_template" field.
func PayloadTemplateNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldPayloadTemplate, vs...))
}

// PayloadTemplateGT applies the GT predicate on the "payload_template" field.
func PayloadTemplateGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldPayloadTemplate, v))
}

// PayloadTemplateGTE applies the GTE predicate on the "payload_template" field.
func PayloadTemplateGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldPayloadTemplate, v))
}

// PayloadTemplateLT applies the LT predicate on the "payload_template" field.
func PayloadTemplateLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldPayloadTemplate, v))
}

// PayloadTemplateLTE applies the LTE predicate on the "payload_template" field.
func PayloadTemplateLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldPayloadTemplate, v))
}

// PayloadTemplateContains applies the Contains predicate on the "payload_template" field.
func PayloadTemplateContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldPayloadTemplate, v))
}

// PayloadTemplateHasPrefix applies the HasPrefix predicate on the "payload_template" field.
func PayloadTemplateHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldPayloadTemplate, v))
}

// PayloadTemplateHasSuffix applies the HasSuffix predicate on the "payload_template" field.
func PayloadTemplateHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldPayloadTemplate, v))
}

// PayloadTemplateIsNil applies the IsNil predicate on the "payload_template" field.
func PayloadTemplateIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldPayloadTemplate))
}

// PayloadTemplateNotNil applies the NotNil predicate on the "payload_template" field.
func PayloadTemplateNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldPayloadTemplate))
}

// PayloadTemplateEqualFold applies the EqualFold predicate on the "payload_template" field.
func PayloadTemplateEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldPayloadTemplate, v))
}

// PayloadTemplateContainsFold applies the ContainsFold predicate on the "payload_template" field.
func PayloadTemplateContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldPayloadTemplate, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
