# Run the following on push & pull request
# Test only
kind: pipeline
type: docker
name: default

clone:
  disable: true

trigger:
  event:
    - push
    - pull_request

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_test
    ports:
      - 5432

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: golang:1.22
    commands:
      - sleep 10
      - go test -count=1 -p 1 ./...
    environment:
      GOSSIP_DATABASE_DRIVER: postgres
      GOSSIP_DATABASE_TESTCONNECTION: host=postgres port=5432 user=admin dbname=app_test password=admin sslmode=disable
      GOSSIP_DATABASE_CONNECTION: host=postgres port=5432 user=admin dbname=app_test password=admin sslmode=disable


---
# Run the following on `promote`
# Test, Release & Deploy
kind: pipeline
type: docker
name: release-deploy

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_test
    ports:
      - 5432

trigger:
  event:
  - promote
  target:
  - production

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: golang:1.22
    commands:
      - sleep 10
      - go test -count=1 -p 1 ./...
    environment:
      GOSSIP_DATABASE_DRIVER: postgres
      GOSSIP_DATABASE_TESTCONNECTION: host=postgres port=5432 user=admin dbname=app_test password=admin sslmode=disable
      GOSSIP_DATABASE_CONNECTION: host=postgres port=5432 user=admin dbname=app_test password=admin sslmode=disable

  - name: build-web
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-web
      tags: latest
      registry: gitea.risky.info
      dockerfile: ./web.dockerfile
      context: .
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD

  - name: build-worker
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-worker
      tags: latest
      registry: gitea.risky.info
      dockerfile: ./worker.dockerfile
      context: .
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD

#  - name: copy-compose
#    image: appleboy/drone-scp
#    settings:
#      host: 173.249.23.177
#      username: idriss
#      key:
#        from_secret: DOCKER_DEPLOY_SSH_KEY
#      port: 7777
#      source:
#        - docker-compose.yml
#      target: /tmp/
#      strip_components: 0
#
#  - name: deploy
#    image: appleboy/drone-ssh
#    environment:
#      GOSSIP_MAIL_PASSWORD:
#        from_secret: MAIL_PASSWORD
#    settings:
#      host: 173.249.23.177
#      username: idriss
#      key:
#        from_secret: DOCKER_DEPLOY_SSH_KEY
#      port: 7777
#      envs: [GOSSIP_MAIL_PASSWORD]
#      script:
#        - export GOSSIP_MAIL_PASSWORD=$GOSSIP_MAIL_PASSWORD
#        - docker stack rm gossip-stack
#        - docker container prune -f
#        - docker image prune -f
#        - docker compose -f /tmp/docker-compose.yml pull
#        - docker stack deploy -c /tmp/docker-compose.yml gossip-stack
#        - docker image prune -f
