kind: pipeline
type: docker
name: default

clone:
  disable: true

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: docker:latest
    commands:
      - apk add --no-cache docker-compose
      - docker-compose -f docker-compose-test.yml up --build -d
      - docker-compose -f docker-compose-test.yml run app
      - docker-compose -f docker-compose-test.yml down

  - name: build-web
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-web:{tag}
      tags: latest
      dockerfile: ./web.dockerfile
      context: .
    when:
      branch:
        - main

  - name: build-worker
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-worker:{tag}
      tags: latest
      dockerfile: ./worker.dockerfile
      context: .
    when:
      branch:
        - main

  - name: deploy
    image: docker
    commands:
      - docker stack deploy --compose-file docker-compose.yml gossip-stack
    environment:
      DOCKER_HOST: tcp://173.249.23.177:2376
    when:
      branch:
        - main
