kind: pipeline
type: docker
name: default

clone:
  disable: true

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: set up Go
    image: golang:1.22
    commands:
      - go version
    environment:
      GOCACHE: /root/.cache/go-build
      GOPATH: /root/go
    volumes:
      - name: go-modules
        path: /root/go/pkg/mod
      - name: go-build-cache
        path: /root/.cache/go-build

  - name: cache dependencies
    image: meltwater/drone-cache
    settings:
      restore: true
      mount:
        - /root/.cache/go-build
        - /root/go/pkg/mod
      key: ${DRONE_COMMIT_BRANCH}-${{DRONE_COMMIT_SHA}}-go
      restore_key: ${DRONE_COMMIT_BRANCH}-
    volumes:
      - name: cache
        path: /tmp/cache

  - name: start containers
    image: docker/compose
    commands:
      - docker-compose -f docker-compose-test.yml up -d
      - sleep 3
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: test
    image: golang:1.22
    commands:
      - go test ./...
    environment:
      GOCACHE: /root/.cache/go-build
      GOPATH: /root/go
    volumes:
      - name: go-modules
        path: /root/go/pkg/mod
      - name: go-build-cache
        path: /root/.cache/go-build

  - name: build-web
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-web:{tag}
      tags: latest
      dockerfile: ./web.dockerfile
      context: .
    when:
      branch:
        - main

  - name: build-worker
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-worker:{tag}
      tags: latest
      dockerfile: ./worker.dockerfile
      context: .
    when:
      branch:
        - main

  - name: deploy
    image: docker
    commands:
      - docker stack deploy --compose-file docker-compose.yml gossip-stack
    environment:
      DOCKER_HOST: tcp://173.249.23.177:2376
    when:
      branch:
        - main

volumes:
  - name: go-modules
    temp: {}
  - name: go-build-cache
    temp: {}
  - name: cache
    host:
      path: /tmp/cache
  - name: docker_socket
    host:
      path: /var/run/docker.sock
