# Run the following on push & pull request
# Test only
kind: pipeline
type: docker
name: default

clone:
  disable: true

trigger:
  event:
    - push
    - pull_request

services:
  - name: redis
    image: redis:alpine
    ports:
      - 6379

  - name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - 5432

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: golang:1.22
    commands:
      - sleep 10
      - go test -count=1 -p 1 ./...
    environment:
      GOSSIP_CACHE_HOSTNAME: redis
      GOSSIP_DATABASE_HOSTNAME: postgres


---
# Run the following on `promote`
# Test, Release & Deploy
kind: pipeline
type: docker
name: release-deploy

services:
  - name: redis
    image: redis:alpine
    ports:
      - 6379

  - name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - 5432

trigger:
  event:
  - promote
  target:
  - production

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: golang:1.22
    commands:
      - sleep 10
      - go test -count=1 -p 1 ./...
    environment:
      GOSSIP_CACHE_HOSTNAME: redis
      GOSSIP_DATABASE_HOSTNAME: postgres

  - name: build-web
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-web
      tags: latest
      registry: gitea.risky.info
      dockerfile: ./web.dockerfile
      context: .
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password

  - name: build-worker
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-worker
      tags: latest
      registry: gitea.risky.info
      dockerfile: ./worker.dockerfile
      context: .
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password

  - name: copy-compose
    image: appleboy/drone-scp
    settings:
      host: 173.249.23.177
      username: idriss
      key:
        from_secret: DOCKER_DEPLOY_SSH_KEY
      port: 7777
      source:
        - docker-compose.yml
      target: /tmp/
      strip_components: 0

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 173.249.23.177
      username: idriss
      key:
        from_secret: DOCKER_DEPLOY_SSH_KEY
      port: 7777
      script:
        - docker stack deploy -c /tmp/docker-compose.yml gossip-stack
