kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone ssh://git@gitea.risky.info:222/risky-info/${DRONE_REPO}.git .
      - git checkout ${DRONE_COMMIT}

  - name: set up Go
    image: golang:1.19
    commands:
      - go version
    environment:
      GOCACHE: /root/.cache/go-build
      GOPATH: /root/go
    volumes:
      - name: go-modules
        path: /root/go/pkg/mod
      - name: go-build-cache
        path: /root/.cache/go-build

  - name: cache dependencies
    image: meltwater/drone-cache
    settings:
      restore: true
      mount:
        - /root/.cache/go-build
        - /root/go/pkg/mod
      key: ${DRONE_COMMIT_BRANCH}-${{DRONE_COMMIT_SHA}}-go
      restore_key: ${DRONE_COMMIT_BRANCH}-
    volumes:
      - name: cache
        path: /tmp/cache

  - name: start containers
    image: docker/compose:alpine-1.29.2
    commands:
      - docker-compose up -d
      - sleep 3
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

  - name: test
    image: golang:1.19
    commands:
      - go test -p 1 ./...
    environment:
      GOCACHE: /root/.cache/go-build
      GOPATH: /root/go
    volumes:
      - name: go-modules
        path: /root/go/pkg/mod
      - name: go-build-cache
        path: /root/.cache/go-build

volumes:
  - name: go-modules
    temp: {}
  - name: go-build-cache
    temp: {}
  - name: cache
    host:
      path: /tmp/cache
  - name: docker_socket
    host:
      path: /var/run/docker.sock

