kind: pipeline
type: docker
name: default

clone:
  disable: true

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_ORIGIN_WITH_AUTH:
        from_secret: GIT_ORIGIN
    commands:
    - git clone $GIT_ORIGIN_WITH_AUTH .
    - git checkout $DRONE_COMMIT

  - name: test
    image: golang:1.22
    commands:
      # Install docker compose then the tests.
      #
      # Add Docker's official GPG key:
      - apt-get update
      - apt-get install - ca-certificates curl
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
      - chmod a+r /etc/apt/keyrings/docker.asc

      # Add the repository to Apt sources:
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - service start docker
      - docker compose -f docker-compose-test.yml up -d
      - sleep 3
      - go test ./...

  - name: build-web
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-web:{tag}
      tags: latest
      dockerfile: ./web.dockerfile
      context: .
    when:
      branch:
        - main

  - name: build-worker
    image: plugins/docker
    settings:
      repo: gitea.risky.info/risky-info/gossip-worker:{tag}
      tags: latest
      dockerfile: ./worker.dockerfile
      context: .
    when:
      branch:
        - main

  - name: deploy
    image: docker
    commands:
      - docker stack deploy --compose-file docker-compose.yml gossip-stack
    environment:
      DOCKER_HOST: tcp://173.249.23.177:2376
    when:
      branch:
        - main
