// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitea.risky.info/risky-info/gossiper/ent/job"
	"gitea.risky.info/risky-info/gossiper/ent/predicate"
	"gitea.risky.info/risky-info/gossiper/ent/user"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetURL sets the "url" field.
func (ju *JobUpdate) SetURL(s string) *JobUpdate {
	ju.mutation.SetURL(s)
	return ju
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (ju *JobUpdate) SetNillableURL(s *string) *JobUpdate {
	if s != nil {
		ju.SetURL(*s)
	}
	return ju
}

// SetMethod sets the "method" field.
func (ju *JobUpdate) SetMethod(j job.Method) *JobUpdate {
	ju.mutation.SetMethod(j)
	return ju
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (ju *JobUpdate) SetNillableMethod(j *job.Method) *JobUpdate {
	if j != nil {
		ju.SetMethod(*j)
	}
	return ju
}

// SetHeaders sets the "headers" field.
func (ju *JobUpdate) SetHeaders(m map[string]string) *JobUpdate {
	ju.mutation.SetHeaders(m)
	return ju
}

// SetData sets the "data" field.
func (ju *JobUpdate) SetData(s string) *JobUpdate {
	ju.mutation.SetData(s)
	return ju
}

// SetNillableData sets the "data" field if the given value is not nil.
func (ju *JobUpdate) SetNillableData(s *string) *JobUpdate {
	if s != nil {
		ju.SetData(*s)
	}
	return ju
}

// ClearData clears the value of the "data" field.
func (ju *JobUpdate) ClearData() *JobUpdate {
	ju.mutation.ClearData()
	return ju
}

// SetEmail sets the "email" field.
func (ju *JobUpdate) SetEmail(s string) *JobUpdate {
	ju.mutation.SetEmail(s)
	return ju
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ju *JobUpdate) SetNillableEmail(s *string) *JobUpdate {
	if s != nil {
		ju.SetEmail(*s)
	}
	return ju
}

// SetPassword sets the "password" field.
func (ju *JobUpdate) SetPassword(s string) *JobUpdate {
	ju.mutation.SetPassword(s)
	return ju
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (ju *JobUpdate) SetNillablePassword(s *string) *JobUpdate {
	if s != nil {
		ju.SetPassword(*s)
	}
	return ju
}

// SetSMTPHost sets the "smtp_host" field.
func (ju *JobUpdate) SetSMTPHost(s string) *JobUpdate {
	ju.mutation.SetSMTPHost(s)
	return ju
}

// SetNillableSMTPHost sets the "smtp_host" field if the given value is not nil.
func (ju *JobUpdate) SetNillableSMTPHost(s *string) *JobUpdate {
	if s != nil {
		ju.SetSMTPHost(*s)
	}
	return ju
}

// ClearSMTPHost clears the value of the "smtp_host" field.
func (ju *JobUpdate) ClearSMTPHost() *JobUpdate {
	ju.mutation.ClearSMTPHost()
	return ju
}

// SetSMTPPort sets the "smtp_port" field.
func (ju *JobUpdate) SetSMTPPort(i int) *JobUpdate {
	ju.mutation.ResetSMTPPort()
	ju.mutation.SetSMTPPort(i)
	return ju
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (ju *JobUpdate) SetNillableSMTPPort(i *int) *JobUpdate {
	if i != nil {
		ju.SetSMTPPort(*i)
	}
	return ju
}

// AddSMTPPort adds i to the "smtp_port" field.
func (ju *JobUpdate) AddSMTPPort(i int) *JobUpdate {
	ju.mutation.AddSMTPPort(i)
	return ju
}

// ClearSMTPPort clears the value of the "smtp_port" field.
func (ju *JobUpdate) ClearSMTPPort() *JobUpdate {
	ju.mutation.ClearSMTPPort()
	return ju
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ju *JobUpdate) SetUserID(id int) *JobUpdate {
	ju.mutation.SetUserID(id)
	return ju
}

// SetUser sets the "user" edge to the User entity.
func (ju *JobUpdate) SetUser(u *User) *JobUpdate {
	return ju.SetUserID(u.ID)
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ju *JobUpdate) ClearUser() *JobUpdate {
	ju.mutation.ClearUser()
	return ju
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ju *JobUpdate) check() error {
	if v, ok := ju.mutation.URL(); ok {
		if err := job.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Job.url": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Method(); ok {
		if err := job.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Job.method": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Email(); ok {
		if err := job.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Job.email": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Password(); ok {
		if err := job.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Job.password": %w`, err)}
		}
	}
	if ju.mutation.UserCleared() && len(ju.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ju.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
	}
	if value, ok := ju.mutation.Method(); ok {
		_spec.SetField(job.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := ju.mutation.Headers(); ok {
		_spec.SetField(job.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := ju.mutation.Data(); ok {
		_spec.SetField(job.FieldData, field.TypeString, value)
	}
	if ju.mutation.DataCleared() {
		_spec.ClearField(job.FieldData, field.TypeString)
	}
	if value, ok := ju.mutation.Email(); ok {
		_spec.SetField(job.FieldEmail, field.TypeString, value)
	}
	if value, ok := ju.mutation.Password(); ok {
		_spec.SetField(job.FieldPassword, field.TypeString, value)
	}
	if value, ok := ju.mutation.SMTPHost(); ok {
		_spec.SetField(job.FieldSMTPHost, field.TypeString, value)
	}
	if ju.mutation.SMTPHostCleared() {
		_spec.ClearField(job.FieldSMTPHost, field.TypeString)
	}
	if value, ok := ju.mutation.SMTPPort(); ok {
		_spec.SetField(job.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedSMTPPort(); ok {
		_spec.AddField(job.FieldSMTPPort, field.TypeInt, value)
	}
	if ju.mutation.SMTPPortCleared() {
		_spec.ClearField(job.FieldSMTPPort, field.TypeInt)
	}
	if ju.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ju.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetURL sets the "url" field.
func (juo *JobUpdateOne) SetURL(s string) *JobUpdateOne {
	juo.mutation.SetURL(s)
	return juo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableURL(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetURL(*s)
	}
	return juo
}

// SetMethod sets the "method" field.
func (juo *JobUpdateOne) SetMethod(j job.Method) *JobUpdateOne {
	juo.mutation.SetMethod(j)
	return juo
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableMethod(j *job.Method) *JobUpdateOne {
	if j != nil {
		juo.SetMethod(*j)
	}
	return juo
}

// SetHeaders sets the "headers" field.
func (juo *JobUpdateOne) SetHeaders(m map[string]string) *JobUpdateOne {
	juo.mutation.SetHeaders(m)
	return juo
}

// SetData sets the "data" field.
func (juo *JobUpdateOne) SetData(s string) *JobUpdateOne {
	juo.mutation.SetData(s)
	return juo
}

// SetNillableData sets the "data" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableData(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetData(*s)
	}
	return juo
}

// ClearData clears the value of the "data" field.
func (juo *JobUpdateOne) ClearData() *JobUpdateOne {
	juo.mutation.ClearData()
	return juo
}

// SetEmail sets the "email" field.
func (juo *JobUpdateOne) SetEmail(s string) *JobUpdateOne {
	juo.mutation.SetEmail(s)
	return juo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableEmail(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetEmail(*s)
	}
	return juo
}

// SetPassword sets the "password" field.
func (juo *JobUpdateOne) SetPassword(s string) *JobUpdateOne {
	juo.mutation.SetPassword(s)
	return juo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillablePassword(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetPassword(*s)
	}
	return juo
}

// SetSMTPHost sets the "smtp_host" field.
func (juo *JobUpdateOne) SetSMTPHost(s string) *JobUpdateOne {
	juo.mutation.SetSMTPHost(s)
	return juo
}

// SetNillableSMTPHost sets the "smtp_host" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableSMTPHost(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetSMTPHost(*s)
	}
	return juo
}

// ClearSMTPHost clears the value of the "smtp_host" field.
func (juo *JobUpdateOne) ClearSMTPHost() *JobUpdateOne {
	juo.mutation.ClearSMTPHost()
	return juo
}

// SetSMTPPort sets the "smtp_port" field.
func (juo *JobUpdateOne) SetSMTPPort(i int) *JobUpdateOne {
	juo.mutation.ResetSMTPPort()
	juo.mutation.SetSMTPPort(i)
	return juo
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableSMTPPort(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetSMTPPort(*i)
	}
	return juo
}

// AddSMTPPort adds i to the "smtp_port" field.
func (juo *JobUpdateOne) AddSMTPPort(i int) *JobUpdateOne {
	juo.mutation.AddSMTPPort(i)
	return juo
}

// ClearSMTPPort clears the value of the "smtp_port" field.
func (juo *JobUpdateOne) ClearSMTPPort() *JobUpdateOne {
	juo.mutation.ClearSMTPPort()
	return juo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (juo *JobUpdateOne) SetUserID(id int) *JobUpdateOne {
	juo.mutation.SetUserID(id)
	return juo
}

// SetUser sets the "user" edge to the User entity.
func (juo *JobUpdateOne) SetUser(u *User) *JobUpdateOne {
	return juo.SetUserID(u.ID)
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (juo *JobUpdateOne) ClearUser() *JobUpdateOne {
	juo.mutation.ClearUser()
	return juo
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (juo *JobUpdateOne) check() error {
	if v, ok := juo.mutation.URL(); ok {
		if err := job.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Job.url": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Method(); ok {
		if err := job.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Job.method": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Email(); ok {
		if err := job.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Job.email": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Password(); ok {
		if err := job.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Job.password": %w`, err)}
		}
	}
	if juo.mutation.UserCleared() && len(juo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Job.user"`)
	}
	return nil
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := juo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
	}
	if value, ok := juo.mutation.Method(); ok {
		_spec.SetField(job.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := juo.mutation.Headers(); ok {
		_spec.SetField(job.FieldHeaders, field.TypeJSON, value)
	}
	if value, ok := juo.mutation.Data(); ok {
		_spec.SetField(job.FieldData, field.TypeString, value)
	}
	if juo.mutation.DataCleared() {
		_spec.ClearField(job.FieldData, field.TypeString)
	}
	if value, ok := juo.mutation.Email(); ok {
		_spec.SetField(job.FieldEmail, field.TypeString, value)
	}
	if value, ok := juo.mutation.Password(); ok {
		_spec.SetField(job.FieldPassword, field.TypeString, value)
	}
	if value, ok := juo.mutation.SMTPHost(); ok {
		_spec.SetField(job.FieldSMTPHost, field.TypeString, value)
	}
	if juo.mutation.SMTPHostCleared() {
		_spec.ClearField(job.FieldSMTPHost, field.TypeString)
	}
	if value, ok := juo.mutation.SMTPPort(); ok {
		_spec.SetField(job.FieldSMTPPort, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedSMTPPort(); ok {
		_spec.AddField(job.FieldSMTPPort, field.TypeInt, value)
	}
	if juo.mutation.SMTPPortCleared() {
		_spec.ClearField(job.FieldSMTPPort, field.TypeInt)
	}
	if juo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := juo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
