// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitea.v3m.net/idriss/gossiper/ent/job"
	"gitea.v3m.net/idriss/gossiper/ent/user"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (jc *JobCreate) SetEmail(s string) *JobCreate {
	jc.mutation.SetEmail(s)
	return jc
}

// SetFromRegex sets the "from_regex" field.
func (jc *JobCreate) SetFromRegex(s string) *JobCreate {
	jc.mutation.SetFromRegex(s)
	return jc
}

// SetNillableFromRegex sets the "from_regex" field if the given value is not nil.
func (jc *JobCreate) SetNillableFromRegex(s *string) *JobCreate {
	if s != nil {
		jc.SetFromRegex(*s)
	}
	return jc
}

// SetURL sets the "url" field.
func (jc *JobCreate) SetURL(s string) *JobCreate {
	jc.mutation.SetURL(s)
	return jc
}

// SetMethod sets the "method" field.
func (jc *JobCreate) SetMethod(j job.Method) *JobCreate {
	jc.mutation.SetMethod(j)
	return jc
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (jc *JobCreate) SetNillableMethod(j *job.Method) *JobCreate {
	if j != nil {
		jc.SetMethod(*j)
	}
	return jc
}

// SetHeaders sets the "headers" field.
func (jc *JobCreate) SetHeaders(m map[string]string) *JobCreate {
	jc.mutation.SetHeaders(m)
	return jc
}

// SetPayloadTemplate sets the "payload_template" field.
func (jc *JobCreate) SetPayloadTemplate(s string) *JobCreate {
	jc.mutation.SetPayloadTemplate(s)
	return jc
}

// SetNillablePayloadTemplate sets the "payload_template" field if the given value is not nil.
func (jc *JobCreate) SetNillablePayloadTemplate(s *string) *JobCreate {
	if s != nil {
		jc.SetPayloadTemplate(*s)
	}
	return jc
}

// SetIsActive sets the "is_active" field.
func (jc *JobCreate) SetIsActive(b bool) *JobCreate {
	jc.mutation.SetIsActive(b)
	return jc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (jc *JobCreate) SetNillableIsActive(b *bool) *JobCreate {
	if b != nil {
		jc.SetIsActive(*b)
	}
	return jc
}

// SetCreatedAt sets the "created_at" field.
func (jc *JobCreate) SetCreatedAt(t time.Time) *JobCreate {
	jc.mutation.SetCreatedAt(t)
	return jc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jc *JobCreate) SetNillableCreatedAt(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetCreatedAt(*t)
	}
	return jc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (jc *JobCreate) SetUserID(id int) *JobCreate {
	jc.mutation.SetUserID(id)
	return jc
}

// SetUser sets the "user" edge to the User entity.
func (jc *JobCreate) SetUser(u *User) *JobCreate {
	return jc.SetUserID(u.ID)
}

// Mutation returns the JobMutation object of the builder.
func (jc *JobCreate) Mutation() *JobMutation {
	return jc.mutation
}

// Save creates the Job in the database.
func (jc *JobCreate) Save(ctx context.Context) (*Job, error) {
	jc.defaults()
	return withHooks(ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JobCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JobCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jc *JobCreate) defaults() {
	if _, ok := jc.mutation.FromRegex(); !ok {
		v := job.DefaultFromRegex
		jc.mutation.SetFromRegex(v)
	}
	if _, ok := jc.mutation.Method(); !ok {
		v := job.DefaultMethod
		jc.mutation.SetMethod(v)
	}
	if _, ok := jc.mutation.IsActive(); !ok {
		v := job.DefaultIsActive
		jc.mutation.SetIsActive(v)
	}
	if _, ok := jc.mutation.CreatedAt(); !ok {
		v := job.DefaultCreatedAt()
		jc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JobCreate) check() error {
	if _, ok := jc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Job.email"`)}
	}
	if v, ok := jc.mutation.Email(); ok {
		if err := job.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Job.email": %w`, err)}
		}
	}
	if _, ok := jc.mutation.FromRegex(); !ok {
		return &ValidationError{Name: "from_regex", err: errors.New(`ent: missing required field "Job.from_regex"`)}
	}
	if _, ok := jc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Job.url"`)}
	}
	if v, ok := jc.mutation.URL(); ok {
		if err := job.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Job.url": %w`, err)}
		}
	}
	if _, ok := jc.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "Job.method"`)}
	}
	if v, ok := jc.mutation.Method(); ok {
		if err := job.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Job.method": %w`, err)}
		}
	}
	if _, ok := jc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Job.is_active"`)}
	}
	if _, ok := jc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	if len(jc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Job.user"`)}
	}
	return nil
}

func (jc *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	)
	if value, ok := jc.mutation.Email(); ok {
		_spec.SetField(job.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := jc.mutation.FromRegex(); ok {
		_spec.SetField(job.FieldFromRegex, field.TypeString, value)
		_node.FromRegex = value
	}
	if value, ok := jc.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := jc.mutation.Method(); ok {
		_spec.SetField(job.FieldMethod, field.TypeEnum, value)
		_node.Method = value
	}
	if value, ok := jc.mutation.Headers(); ok {
		_spec.SetField(job.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := jc.mutation.PayloadTemplate(); ok {
		_spec.SetField(job.FieldPayloadTemplate, field.TypeString, value)
		_node.PayloadTemplate = value
	}
	if value, ok := jc.mutation.IsActive(); ok {
		_spec.SetField(job.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := jc.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := jc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   job.UserTable,
			Columns: []string{job.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.job_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (jcb *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if jcb.err != nil {
		return nil, jcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Job, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JobCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
